spring:
  jwt:
    secret: 6a85c93d2e84649584ee628f3f25b13d8e4ca32a98eaa0840a613ad2ed4eea1b
  application:
    name: demo
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://localhost:5432/database_name
  jpa:
    hibernate:
      ddl-auto: create-drop (change to create, update or what suit best your need )
    show-sql: true
    properties:
      hibernate:
        format_sql: true
